# Generated by Django 5.0.3 on 2024-05-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='experience',
            field=models.CharField(default='gyu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register',
            name='fname',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register',
            name='lname',
            field=models.CharField(default='fefed', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register',
            name='phone',
            field=models.CharField(default=63883897699, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register',
            name='qualification',
            field=models.CharField(default=34, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register',
            name='resume',
            field=models.ImageField(default='dcdc.png', upload_to=None),
            preserve_default=False,
        ),
    ]
