# Generated by Django 5.0.3 on 2024-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_register_experience_customer_register_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_register',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='resume',
            field=models.ImageField(null=True, upload_to='./resume/'),
        ),
    ]
