# Generated by Django 5.0.3 on 2024-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_register_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_register',
            name='resume',
            field=models.FileField(null=True, upload_to='cv_uploads/%Y/%m/%d/'),
        ),
    ]
