# Generated by Django 5.0.3 on 2024-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company_register'),
            preserve_default=False,
        ),
    ]
